version: '3'

services:

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /home/jkim/webapps/nginx-proxy-manager/production.json:/app/config/production.json
      - /home/jkim/webapps/nginx-proxy-manager/data:/data
      - /home/jkim/webapps/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  db:
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /home/jkim/webapps/nginx-proxy-manager/data/mysql:/var/lib/mysql
