version: "3.7"

x-common-env:
  &common-environment
  PUID: ${PUID}
  GUID: ${GUID}
  TZ: ${TZ}

x-media-volume:
  &media-volume 
  - type: bind
    source: ${VEGA_MEDIA}/configs/plex
    target: /config
  - type: bind
    source: ${VEGA_MEDIA}
    target: ${MEDIA}

services:
  plex:
    build: plex/.
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment: *common-environment
    volumes: *media-volume
