version: "3.7"

x-common-env:
  &common-environment
  PUID: ${PUID}
  GUID: ${GUID}
  TZ: ${TZ}

x-media-volume:
  &media-volume 
  - type: bind
    source: ${VEGA_MEDIA}
    target: ${MEDIA}

services:
  sonarr:
    build: sonarr/.
    container_name: sonarr
    ports:
      - "8989:8989"
    environment: *common-environment
    volumes: *media-volume

  radarr:
    build: radarr/.
    container_name: radarr
    ports: 
      - "7878:7878"
    environment: *common-environment
    volumes: *media-volume

  lidarr:
    build: lidarr
    container_name: lidarr
    ports:
      - "8686:8686"
    environment: *common-environment
    volumes: *media-volume

  jackett:
    build: jackett/.
    container_name: jackett
    ports:
      - "9117:9117"
    environment: *common-environment

  lazylibrarian:
    build: lazylibrarian/.
    container_name: lazylibrarian
    ports:
      - "5299:5299"
    environment: *common-environment
    volumes:
      - type: bind
        source: ${VEGA_MEDIA_BOOKS}
        target: /books
      - type: bind
        source: ${VEGA_MEDIA_TEMP}
        target: /download


