version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - /home/jkim/webapps/nextclouddb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /home/jkim/webapps/nextcloud:/var/www/html
    restart: always
    depends_on:
      - db
